#!/usr/bin/env python3
"""8-bit Song Maker for Buzzer."""

import re
from pathlib import Path

NOTE_FREQUENCIES = {
    "C4": 262, "C#4": 277, "D4": 294, "D#4": 311, "E4": 330,
    "F4": 349, "F#4": 370, "G4": 392, "G#4": 415, "A4": 440,
    "A#4": 466, "B4": 494,
    "C5": 523, "C#5": 554, "D5": 587, "D#5": 622, "E5": 659,
    "F5": 698, "F#5": 740, "G5": 784, "G#5": 831, "A5": 880,
    "A#5": 932, "B5": 988,
    "C6": 1047, "C#6": 1109, "D6": 1175, "D#6": 1245, "E6": 1319,
    "F6": 1397, "F#6": 1480, "G6": 1568, "G#6": 1661, "A6": 1760,
    "A#6": 1865, "B6": 1976,
}

TOKEN_RE = re.compile(r"^([A-Ga-g](?:#)?[4-6]|R):([1-9][0-9]*)$")


def parse_song(song_text):
    notes = []

    for token in song_text.split():
        match = TOKEN_RE.match(token)
        if not match:
            raise ValueError(
                f"Invalid token '{token}'. Use NOTE:DURATION, e.g. C4:200 or R:100."
            )

        name = match.group(1).upper()
        duration = int(match.group(2))
        frequency = 0 if name == "R" else NOTE_FREQUENCIES.get(name)

        if name != "R" and frequency is None:
            raise ValueError(f"Unsupported note: {name}")

        notes.append((frequency, duration))

    if not notes:
        raise ValueError("The song cannot be empty.")

    return notes


def generate_cpp(notes, buzzer_pin):
    lines = [
        "// Generated by 8-bit Song Maker for Buzzer",
        "",
        f"const int BUZZER_PIN = {buzzer_pin};",
        "",
        "struct Note {",
        "  int frequency;",
        "  int duration;",
        "};",
        "",
        "const Note song[] = {",
    ]

    for frequency, duration in notes:
        lines.append(f"  {{{frequency}, {duration}}},")

    lines += [
        "};",
        "",
        "const size_t SONG_LENGTH = sizeof(song) / sizeof(song[0]);",
        "",
        "void playSong() {",
        "  for (size_t i = 0; i < SONG_LENGTH; ++i) {",
        "    if (song[i].frequency > 0) {",
        "      tone(BUZZER_PIN, song[i].frequency, song[i].duration);",
        "    } else {",
        "      noTone(BUZZER_PIN);",
        "    }",
        "    delay(song[i].duration);",
        "    noTone(BUZZER_PIN);",
        "    delay(20);",
        "  }",
        "}",
        "",
        "void setup() {",
        "  pinMode(BUZZER_PIN, OUTPUT);",
        "}",
        "",
        "void loop() {",
        "  playSong();",
        "  delay(500);",
        "}",
        "",
    ]
    return "\n".join(lines)


def main():
    print("=== 8-bit Song Maker for Buzzer ===")
    print("Example: C4:180 D4:180 E4:180 G4:300 R:120")
    print()

    song_text = input("Song: ").strip()

    try:
        notes = parse_song(song_text)
    except ValueError as error:
        print(f"Error: {error}")
        raise SystemExit(1)

    pin_text = input("Buzzer GPIO [15]: ").strip()
    try:
        buzzer_pin = int(pin_text) if pin_text else 15
    except ValueError:
        print("Error: GPIO must be a number.")
        raise SystemExit(1)

    output_text = input("Output filename [generated_song.cpp]: ").strip()
    output_path = Path(output_text or "generated_song.cpp")

    output_path.write_text(
        generate_cpp(notes, buzzer_pin),
        encoding="utf-8"
    )

    print()
    print(f"Created: {output_path}")
    print(f"Notes: {len(notes)}")
    print(f"Buzzer GPIO: {buzzer_pin}")


if __name__ == "__main__":
    main()
