#!/usr/bin/env python3
"""Convert a MIDI file into monophonic buzzer-friendly C++ note data."""

from __future__ import annotations

import argparse
from pathlib import Path

import mido

DEFAULT_BUZZER_PIN = 25
MIN_FREQUENCY = 31
MAX_FREQUENCY = 5000
MIN_DURATION_MS = 30


def midi_to_freq(note: int) -> int:
    """Convert a MIDI note number to its nearest frequency in Hz."""
    return round(440 * (2 ** ((note - 69) / 12)))


def read_midi_notes(path: Path) -> list[tuple[float, float, int, int]]:
    """Read note intervals as (start_seconds, end_seconds, note, velocity)."""
    midi = mido.MidiFile(str(path))
    merged = mido.merge_tracks(midi.tracks)

    tempo = 500000  # MIDI default: 120 BPM
    current_seconds = 0.0
    active: dict[tuple[int, int], list[tuple[float, int]]] = {}
    notes: list[tuple[float, float, int, int]] = []

    for msg in merged:
        current_seconds += mido.tick2second(
            msg.time, midi.ticks_per_beat, tempo
        )

        if msg.type == "set_tempo":
            tempo = msg.tempo
            continue

        if msg.type != "note_on" and msg.type != "note_off":
            continue

        key = (getattr(msg, "channel", 0), msg.note)

        if msg.type == "note_on" and msg.velocity > 0:
            active.setdefault(key, []).append(
                (current_seconds, msg.velocity)
            )
            continue

        starts = active.get(key)
        if not starts:
            continue

        start, velocity = starts.pop()
        if not starts:
            del active[key]

        if current_seconds > start:
            notes.append(
                (start, current_seconds, msg.note, velocity)
            )

    return notes


def make_monophonic(
    notes: list[tuple[float, float, int, int]],
) -> list[tuple[int, int]]:
    """
    Reduce MIDI polyphony to one note at a time.

    At every time segment, the highest-velocity active note wins.
    If velocities tie, the higher pitch wins.
    """
    boundaries = sorted(
        {time for start, end, _, _ in notes for time in (start, end)}
    )

    if len(boundaries) < 2:
        return []

    result: list[tuple[int, int]] = []

    for start, end in zip(boundaries, boundaries[1:]):
        duration_ms = round((end - start) * 1000)
        if duration_ms <= 0:
            continue

        active = [
            (velocity, note)
            for note_start, note_end, note, velocity in notes
            if note_start <= start < note_end
        ]

        if active:
            _, note = max(active)
            frequency = midi_to_freq(note)
            if MIN_FREQUENCY <= frequency <= MAX_FREQUENCY:
                item = (frequency, duration_ms)
            else:
                item = (0, duration_ms)
        else:
            item = (0, duration_ms)

        if item[1] < MIN_DURATION_MS:
            continue

        if result and result[-1][0] == item[0]:
            result[-1] = (result[-1][0], result[-1][1] + item[1])
        else:
            result.append(item)

    return result


def write_header(
    output: Path,
    notes: list[tuple[int, int]],
    buzzer_pin: int,
) -> None:
    lines = [
        "// Generated by 8-bit Song Maker for Buzzer.",
        "// Source: MIDI converted to monophonic buzzer data.",
        "",
        f"#define BUZZER_PIN {buzzer_pin}",
        "",
        "struct Note {",
        "  int freq;",
        "  int time;",
        "};",
        "",
        "const Note song[] = {",
    ]

    for frequency, duration in notes:
        lines.append(f"  {{{frequency}, {duration}}},")

    lines.extend(
        [
            "  {0, 0}",
            "};",
            "",
            "const size_t SONG_LENGTH = sizeof(song) / sizeof(song[0]) - 1;",
            "",
        ]
    )

    output.write_text("\n".join(lines), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert a MIDI file into buzzer-friendly song.h data."
    )
    parser.add_argument("input", type=Path, help="Input .mid/.midi file")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path("song.h"),
        help="Output header path (default: song.h)",
    )
    parser.add_argument(
        "--buzzer-pin",
        type=int,
        default=DEFAULT_BUZZER_PIN,
        help=f"Buzzer GPIO number (default: {DEFAULT_BUZZER_PIN})",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    if not args.input.is_file():
        raise SystemExit(f"Input MIDI file not found: {args.input}")

    if args.buzzer_pin < 0:
        raise SystemExit("Buzzer GPIO must be 0 or greater.")

    try:
        midi_notes = read_midi_notes(args.input)
    except (OSError, ValueError) as error:
        raise SystemExit(f"Could not read MIDI file: {error}") from error

    notes = make_monophonic(midi_notes)
    if not notes:
        raise SystemExit("No usable MIDI notes were found.")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    write_header(args.output, notes, args.buzzer_pin)

    print("Finished!")
    print(f"Source: {args.input}")
    print(f"Notes: {len(notes)}")
    print(f"Created: {args.output}")


if __name__ == "__main__":
    main()
